package Vistas;

import AccesoADatos.MateriaData;
import Entidades.Materia;
import javax.swing.JOptionPane;

public class FormularioMateria extends javax.swing.JInternalFrame {

    public FormularioMateria() {
        initComponents();

        jbEliminar.setEnabled(false);
        jbNuevo.setEnabled(false);
        
        //Inhabilita los botones 'Nuevo' y 'Eliminar'
        jbNuevo.setEnabled(false);
        jbEliminar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfCodigo = new javax.swing.JTextField();
        jtfAño = new javax.swing.JTextField();
        jtfNombre = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jbNuevo = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jrbEstado = new javax.swing.JRadioButton();

        setPreferredSize(new java.awt.Dimension(600, 500));

        jLabel1.setText("Código");

        jLabel2.setText("Nombre");

        jLabel3.setText("Año");

        jLabel4.setText("Estado");

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Formulario de Materia");

        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(55, 55, 55))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(69, 69, 69))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(51, 51, 51)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtfCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(jtfNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfAño))
                                .addGap(38, 38, 38)
                                .addComponent(jbBuscar))
                            .addComponent(jrbEstado)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbNuevo)
                        .addGap(56, 56, 56)
                        .addComponent(jbEliminar)
                        .addGap(60, 60, 60)
                        .addComponent(jbGuardar)
                        .addGap(59, 59, 59)
                        .addComponent(jbSalir)))
                .addContainerGap(100, Short.MAX_VALUE))
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbBuscar)
                        .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jrbEstado))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNuevo)
                    .addComponent(jbEliminar)
                    .addComponent(jbGuardar)
                    .addComponent(jbSalir))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        //Si no completa el campo 'Código'
        if (jtfCodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe completar el campo Código");
            
        } else {
            try {
                //Asignamos a una variable el dato ingresado en la vista
                int codigo = Integer.parseInt(jtfCodigo.getText());

                //Instanciamos una materia y materiaData para usar luego
                MateriaData md = new MateriaData();
                Materia materiaBuscada = new Materia();

                //Buscamos una materia por código usando buscar de materiaData
                materiaBuscada = md.buscarMateria(codigo);
                
                //Mostramos en la vista los datos de la materia encontrada
                jtfNombre.setText(materiaBuscada.getNombre());
                jtfAño.setText(Integer.toString(materiaBuscada.getAnio()));
                jrbEstado.setSelected(materiaBuscada.isActivo());
                
                //Habilitamos los botones 'Nuevo' y 'Eliminar'
                jbNuevo.setEnabled(true);
                jbEliminar.setEnabled(true);

            } catch (NumberFormatException nfe) {
                //si ingresa letras o símbolos
                JOptionPane.showMessageDialog(this, "Ingrese sólo números");
                jtfCodigo.setText("");
            } catch (NullPointerException npe) {
                //si no existe materia con el código tipeado en la vista, salta el JOptionPane del método buscarMateria
            }
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // Invisibiliza, deselecciona y cierra la ventana
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        //Si el campo Código está vacío
        if (jtfCodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Complete el campo 'Código'");
            
        } else {
            try {
                //Instanciamos materia y materiaData para usar luego
                Materia m = new Materia();
                MateriaData md = new MateriaData();
                
                //Creamos una variable con el código tipeado en la vista
                int codigo = Integer.parseInt(jtfCodigo.getText());
                
                //Buscamos la materia con ese código y lo enviamos a materia ya creada
                m = md.buscarMateria(codigo);
                
                //Eliminamos la materia llamando al método eliminarMateria de materiaData
                md.eliminarMateria(m.getIdMateria());
                
                //Limpiamos los campos de la vista
                jtfCodigo.setText("");
                jtfAño.setText("");
                jtfNombre.setText("");
                jrbEstado.setSelected(false);
                
            } catch (NumberFormatException ex) {
                //si no ingresa números enteros
                JOptionPane.showMessageDialog(null, "Ingrese sólo números enteros");
            }
        }
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
         //Limpia la pantalla para cargar una materia nueva
        jtfCodigo.setText("");
        jtfAño.setText("");
        jtfNombre.setText("");
        jrbEstado.setSelected(false);
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        //Instanciamos materiaData para usar luego
        MateriaData md = new MateriaData();

        try {
            //creamos las variables y asignamos los valores tipeados en la vista
            int codigo = Integer.parseInt(jtfCodigo.getText());
            String nombre = jtfNombre.getText();
            int anio = Integer.parseInt(jtfAño.getText());
            boolean estado = jrbEstado.isSelected();
            //Instanciamos una materia con los parámetros anteriores
            Materia m = new Materia(codigo,nombre,anio,estado);
            
            //declaramos una variable bandera por si ya existe el código tipeado en vista
            boolean existeCodigo = false;
            
            //Recorremos la lista de materias existentes
            for (Materia existingMateria : md.listarMateria()) {
                
                //BUSCA SI LA MATERIA EXISTE DENTRO DEL LISTADO DE MATERIAS
                if (existingMateria.getIdMateria() == m.getIdMateria()) {
                    //Si existe la materia seteamos el id para poder acceder al método modificar; si no existe se activa la bandera más abajo 
                    //m.setIdMateria(md.buscarMateria(m.getCodigo()).getIdMateria());
                    existeCodigo = true;
                    break;
                }
            }
            //Si existe la materia usa el método modificarMateria; si no, guardarMateria
            if (existeCodigo == true) {
                md.modificarMateria(m);
            } else {
                md.guardarMateria(m);
            }

            //Habilitamos los botones 'Eliminar' y 'Nuevo'
            jbEliminar.setEnabled(true);
            jbNuevo.setEnabled(true);
            
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Complete el campo 'Código'");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null,"Use sólo números enteros para 'Código'");
        }
    }//GEN-LAST:event_jbGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbSalir;
    private javax.swing.JRadioButton jrbEstado;
    private javax.swing.JTextField jtfAño;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables
}
