
package Vistas;

import javax.swing.JOptionPane;


public class MenuPrincipal extends javax.swing.JFrame {

    public MenuPrincipal() {
        initComponents();
        
        //Abre la ventana del menú en el centro
        this.setLocationRelativeTo(null);
        
        //Impide que se modifique el tamaño de la ventana
        this.setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiFormularioAlumno = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiFormularioMateria = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiManejoIns = new javax.swing.JMenuItem();
        jmiManejoNotas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmiAlumnosPorMat = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Escritorio.setPreferredSize(new java.awt.Dimension(900, 500));

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1004, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1004, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setText("Alumno");

        jmiFormularioAlumno.setText("Formulario de Alumno");
        jmiFormularioAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioAlumnoActionPerformed(evt);
            }
        });
        jMenu1.add(jmiFormularioAlumno);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Materia");

        jmiFormularioMateria.setText("Formulario de Materia");
        jmiFormularioMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioMateriaActionPerformed(evt);
            }
        });
        jMenu2.add(jmiFormularioMateria);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Administracion");

        jmiManejoIns.setText("Manejo de Inscripciones");
        jmiManejoIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManejoInsActionPerformed(evt);
            }
        });
        jMenu3.add(jmiManejoIns);

        jmiManejoNotas.setText("Manipulacion de Notas");
        jmiManejoNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManejoNotasActionPerformed(evt);
            }
        });
        jMenu3.add(jmiManejoNotas);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Consultas");

        jmiAlumnosPorMat.setText("Alumnos por Materia");
        jmiAlumnosPorMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAlumnosPorMatActionPerformed(evt);
            }
        });
        jMenu4.add(jmiAlumnosPorMat);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Salir");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiFormularioMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioMateriaActionPerformed
        Escritorio.removeAll(); //para que cierre las ventanas que pudieran estar abiertas
        Escritorio.repaint(); //para que lo redibuje
        FormularioMateria fm = new FormularioMateria(); //instancia la ventana (aún invis.)
        fm.setVisible(true); //la hace visible
        Escritorio.add(fm); //la agrega al escritorio
        Escritorio.moveToFront(fm); //la abre y trae adelante
    }//GEN-LAST:event_jmiFormularioMateriaActionPerformed

    private void jmiManejoInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManejoInsActionPerformed
        Escritorio.removeAll(); //para que cierre las ventanas que pudieran estar abiertas
        Escritorio.repaint(); //para que lo redibuje
        FormularioInscripcion fi = new FormularioInscripcion(); //inst. la ventana (invis.)
        fi.setVisible(true); //la hace visible
        Escritorio.add(fi); //la agrega al escritorio
        Escritorio.moveToFront(fi); //la abre y trae adelante
    }//GEN-LAST:event_jmiManejoInsActionPerformed

    private void jmiManejoNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManejoNotasActionPerformed
        Escritorio.removeAll(); //para que cierre las ventanas ue pudieran estar abiertas
        Escritorio.repaint(); //para que lo redibuje
        CargaDeNotas cdn = new CargaDeNotas(); //instancia la ventana (aún invisible)
        cdn.setVisible(true); //la hace visible
        Escritorio.add(cdn); //la agrega al escritorio
        Escritorio.moveToFront(cdn); //la abre y trae adelante
    }//GEN-LAST:event_jmiManejoNotasActionPerformed

    private void jmiAlumnosPorMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAlumnosPorMatActionPerformed
        Escritorio.removeAll(); //para que cierre las ventanas que pudieran estar abiertas
        Escritorio.repaint(); //para que lo redibuje
        ListadoAlumnosPorMateria lam = new ListadoAlumnosPorMateria(); //inst.la ventana
        lam.setVisible(true); //la hace visible
        Escritorio.add(lam); //la agrega al escritorio
        Escritorio.moveToFront(lam); //la abre y trae adelante
    }//GEN-LAST:event_jmiAlumnosPorMatActionPerformed

    private void jmiFormularioAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioAlumnoActionPerformed
        Escritorio.removeAll(); //para que cierre las ventanas que pudieran estar abiertas
        Escritorio.repaint(); //para que lo redibuje
        FormularioAlumno fa = new FormularioAlumno(); //instancia la ventana (aún invis.)
        fa.setVisible(true); //la hace visible
        Escritorio.add(fa); //la agrega al escritorio
        Escritorio.moveToFront(fa); //la abre y trae adelante
    }//GEN-LAST:event_jmiFormularioAlumnoActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
       //Llama al método para cerrar la aplicación completa
        cerrar();
    }//GEN-LAST:event_jMenu5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jmiAlumnosPorMat;
    private javax.swing.JMenuItem jmiFormularioAlumno;
    private javax.swing.JMenuItem jmiFormularioMateria;
    private javax.swing.JMenuItem jmiManejoIns;
    private javax.swing.JMenuItem jmiManejoNotas;
    // End of variables declaration//GEN-END:variables

    public void cerrar() {
        //Establece los nombre de los dos botones del JOptionPane
        String botones[] = {"Cerrar", "Cancelar"};
        
        //Asigna el JOptionPane a una variable y si elige 'si'...
        int eleccion = JOptionPane.showOptionDialog(this, "¿Desea cerrar la aplicación?", "Salir", 0, 0, null, botones, this);
        
        if (eleccion == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }
}
